#include <iostream>
#include <string>
#include <fstream>
class Player
  {
    private:
    // class pet
    //   {
    //   private:
    //       int health;
    //   public:
    //       pet();
    //       int gethealth();
    //   };
    //accountclass
    //shopclass
    //clockclass
    int petnumber;
    std::string username;
    public:
      Player();
      void setusername(std::string username);
      std::string getusername();
      int getpetnumer();
    };
  // pet::pet()
  //   {
  //     health = 70;
  //   }
  // int pet::gethealth()
  //   {
  //     return health;
  //   }
  Player::Player()
    {
      petnumber = 0;
      username = "";
    }
  int Player::getpetnumer()
    {
      return petnumber;
    }
  std::string Player::getusername()
    {
      return username;
    }
  void Player::setusername(std::string username)
    {
      this->username = username;
    }


  void newplayermenu(Player * p)
    {
      std::cout << "First please enter your username" << std::endl;
      std::string i;
      std::cin >> i;
      p->setusername(i);
      std::cout << "Your username is " << p->getusername()<< std::endl;
      std::ofstream userinfo;
      userinfo.open(std::string(i+".txt").c_str());
      userinfo << p->getusername();
      userinfo<< "\n";
      userinfo<< p->getpetnumer();
      userinfo.close();
      //pet * pp = new pet;
      //pp->gethealth();
      std::cout << "A text file has been made containing your username and data" << std::endl;
      std::cout << "For your virtual pet to work DO NOT EDIT this file" << std::endl;
      std::cout << "The program will now close and you can recompile with your account information" << std::endl;

    }
  int main(int argc, char** argv)
    {
      if(argc<=1)
      {
        std::cout << "Hello and welcome to your pet adventure!" << std::endl;
        std::cout << "We see you tried to complie without a text file. Press one if you are a new player" << std::endl;
        int i = 0;
        std::cin >> i;
        if(i == 1)
        {
          std::cout << "Welcome!" << std::endl;
          Player *p = new Player;
          newplayermenu(p);
        }
        else
        {
          std::cout << "Not a new player? Hmm... Then try entering your .txt file name again" << std::endl;
        }
      }
      else
        {
          std::cout << "here" << std::endl;
          std::ifstream userfile;
          std::string line;
          userfile.open(argv[1]);
          if(userfile.is_open())
          {
            while(!userfile.eof())
              {
                std::getline(userfile,line);
                std::cout << line << std::endl;
              }
          }
        }
    }
